### ISSUE TITLE
Ruilen?

### ISSUE THREAD

**Issue by Ravichotkan** [Badmuts/Machiavelli#1]
Hallo,

Ik heb vorige week jullie bordspel gekocht, maar speel het eigenlijk niet meer. 
Kan ik het spel ruilen? Ik heb het bonnetje nog.

![259401f0-9ff1-4549-b135-898dcf659d0b](https://cloud.githubusercontent.com/assets/12196682/24201969/f7df679e-0f11-11e7-85ea-1d9868b61f4e.png)

**Comment by Stukongeluk** [comment]
@Ravichotkan 

Beste klant,

Omdat we dit spel niet meer op voorraad hebben en 99% van mensen die het hebben gespeeld spontaan een erectiestoornis kregen, hebben we het uit de schrappen gehaald. Dit betekent dat we het ook niet meer ruilen.

Met vriendelijke groet,
TheLegend27

**Comment by Badmuts** [comment]
Hahahaha
